// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCpuData() {
  return window['go']['main']['App']['GetCpuData']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}
